'use strict';
// Local maintenance only. Node.js 18+, no packages required.
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..');
const TABLE=[46,47,18,2,53,8,23,32,15,50,10,31,58,3,45,35,27,43,5,49,33,9,42,19,29,28,14,39,12,38,41,13,37,48,7,16,24,55,40,61,26,17,0,1,60,51,30,4,22,25,54,21,56,59,6,63,57,62,11,36,20,34,44,52];
function sign(params,img,sub,now=Math.floor(Date.now()/1000)){const source=img+sub;if(source.length!==64)throw Error('签名密钥格式异常');const key=TABLE.map(i=>source[i]).join('').slice(0,32);const values={...params,wts:now};const query=Object.keys(values).sort().map(k=>encodeURIComponent(k)+'='+encodeURIComponent(String(values[k]).replace(/[!'()*]/g,''))).join('&');return query+'&w_rid='+crypto.createHash('md5').update(query+key).digest('hex');}
function validate(config){if(!Number.isInteger(config.maxVideosPerChannel)||config.maxVideosPerChannel<1||config.maxVideosPerChannel>30)throw Error('maxVideosPerChannel 必须为 1～30');if(!Array.isArray(config.channels)||!config.channels.length||config.channels.length>20)throw Error('请配置 1～20 个频道');const names=new Set(),ids=new Set();for(const c of config.channels){if(typeof c.name!=='string'||!c.name.trim()||/[\r\n\[\]|]/.test(c.name)||c.name!==c.name.trim()||!/^\d+$/.test(String(c.mid))||Number(c.mid)<1||names.has(c.name)||ids.has(String(c.mid)))throw Error('频道名称或 UID 无效/重复');names.add(c.name);ids.add(String(c.mid));}return config;}
async function getJSON(url){let response;try{response=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://space.bilibili.com/',...(process.env.BILIBILI_COOKIE?{Cookie:process.env.BILIBILI_COOKIE}:{})},signal:AbortSignal.timeout(20000),redirect:'error'});}catch{throw Error('网络连接失败或超时，请稍后再试');}if(!response.ok)throw Error('B站返回 HTTP '+response.status+'，已停止，原清单不会被修改。家庭网络也可能触发风控，请勿连续重试');try{return await response.json();}catch{throw Error('B站返回了非 JSON 响应，已停止');}}
function render(config,lists){let text='# 自动生成的候选清单，请审核并删除不合适的视频后再批准。\n# 生成时间：'+new Date().toISOString()+'\n# 每次生成会替换候选文件；请先保存你的审核结果。\n\n';config.channels.forEach((c,i)=>{text+='['+c.name+']\n';const videos=lists[i];const seen=new Set();for(const v of videos.slice(0,config.maxVideosPerChannel)){if(!/^BV[0-9A-Za-z]{10}$/.test(v.bvid)||typeof v.title!=='string')throw Error(c.name+' 的视频数据格式异常');if(seen.has(v.bvid))continue;seen.add(v.bvid);const title=v.title.replace(/[\r\n|]/g,' ').trim();text+=v.bvid+' | '+title+'\n';}text+='\n';});return text;}
function atomicWrite(file,text){const temp=file+'.tmp';try{fs.writeFileSync(temp,text,'utf8');fs.renameSync(temp,file);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
function approve(){const file=path.join(ROOT,'videos.candidates.txt');if(!fs.existsSync(file))throw Error('没有候选清单，请先运行 node scripts/update.cjs');const {parseVideos}=require(path.join(ROOT,'app.js'));const text=fs.readFileSync(file,'utf8');const result=parseVideos(text);if(result.errors.length)throw Error('候选清单有错误：'+result.errors.join('；'));const target=path.join(ROOT,'videos.txt');if(fs.existsSync(target)){const backupDir=path.join(ROOT,'.local-backups');fs.mkdirSync(backupDir,{recursive:true});fs.copyFileSync(target,path.join(backupDir,'videos-'+Date.now()+'.txt'));}atomicWrite(target,text.replace('# 自动生成的候选清单，请审核并删除不合适的视频后再批准。','# 家长已审核的视频清单。'));console.log('已将审核后的候选清单替换 videos.txt。旧清单已备份至 .local-backups。请只上传网站文件和 videos.txt。');}
async function main(){const args=process.argv.slice(2);if(args.length && !(args.length===1&&args[0]==='--approve'))throw Error('用法：node scripts/update.cjs 或 node scripts/update.cjs --approve');if(args[0]==='--approve'){approve();return;}const config=validate(JSON.parse(fs.readFileSync(path.join(ROOT,'channels.json'),'utf8').replace(/^\uFEFF/,'')));const nav=await getJSON('https://api.bilibili.com/x/web-interface/nav');const keys=nav.data?.wbi_img;if(!keys)throw Error('无法取得 B站签名信息，原清单不会被修改');const key=url=>new URL(url).pathname.split('/').pop().split('.')[0];const lists=[];for(let i=0;i<config.channels.length;i++){const c=config.channels[i];console.log('读取 '+c.name+'…');const query=sign({mid:String(c.mid),pn:1,ps:30,order:'pubdate'},key(keys.img_url),key(keys.sub_url));const data=await getJSON('https://api.bilibili.com/x/space/wbi/arc/search?'+query);if(data.code!==0)throw Error(c.name+' 请求失败，返回码 '+data.code+'。已停止，原清单和候选文件均保持不变');const videos=data.data?.list?.vlist;if(!Array.isArray(videos)||!videos.length)throw Error(c.name+' 未返回视频；为避免误清空，已停止');lists.push(videos);if(i<config.channels.length-1)await new Promise(resolve=>setTimeout(resolve,2000));}const text=render(config,lists);atomicWrite(path.join(ROOT,'videos.candidates.txt'),text);console.log('候选清单已生成：videos.candidates.txt。videos.txt 未改变。审核后运行 node scripts/update.cjs --approve');}
module.exports={sign,validate,render,atomicWrite};if(require.main===module)main().catch(error=>{console.error('更新失败：'+error.message);process.exitCode=1;});
